In [1]:
from sklearn.manifold import TSNE
import pandas as pd
import numpy as np
import time

In [2]:
df = np.loadtxt("../California.csv",delimiter=",")

In [7]:
df = np.random.rand(1000000,2)

In [6]:
df.shape, np.max(df, axis=0), np.min(df, axis=0)

((140820, 2),
 array([41.9950612,  9.37966  ]),
 array([ -17.3913746, -124.3578042]))

In [ ]:
 np.max(df, axis=0)

In [8]:
tsne = TSNE(n_components=2, random_state=42, n_jobs=25, verbose=10,n_iter=1500)
start = time.time()
X_tsne = tsne.fit_transform(df)
end = time.time()
print("Time taken by scikit learn:",(end-start))
with open("real_Data/california_1M"+"scikit"+".npy", 'wb') as f:
    np.save(f,X_tsne)
    np.save(f,df)

[t-SNE] Computing 91 nearest neighbors...
[t-SNE] Indexed 1000000 samples in 0.430s...
[t-SNE] Computed neighbors for 1000000 samples in 12.277s...
[t-SNE] Computed conditional probabilities for sample 1000 / 1000000
[t-SNE] Computed conditional probabilities for sample 2000 / 1000000
[t-SNE] Computed conditional probabilities for sample 3000 / 1000000
[t-SNE] Computed conditional probabilities for sample 4000 / 1000000
[t-SNE] Computed conditional probabilities for sample 5000 / 1000000
[t-SNE] Computed conditional probabilities for sample 6000 / 1000000
[t-SNE] Computed conditional probabilities for sample 7000 / 1000000
[t-SNE] Computed conditional probabilities for sample 8000 / 1000000
[t-SNE] Computed conditional probabilities for sample 9000 / 1000000
[t-SNE] Computed conditional probabilities for sample 10000 / 1000000
[t-SNE] Computed conditional probabilities for sample 11000 / 1000000
[t-SNE] Computed conditional probabilities for sample 12000 / 1000000
[t-SNE] Computed cond

In [10]:
with open('gas_discrete.npy', 'wb') as f:
    np.save(f,embedding)
    np.save(f,df)

In [4]:
df

array([[ 0, 36, 37, ..., 30, 10,  8],
       [ 0, 36, 37, ..., 38, 14, 13],
       [ 0, 36, 37, ..., 45, 24, 20],
       ...,
       [24, 44,  3, ..., 54, 28, 21],
       [24, 44,  3, ..., 57, 28, 22],
       [24, 44,  3, ..., 55, 28, 21]])

In [5]:
df[0]

array([ 0, 36, 37, 61, 13, 30, 10,  8])

In [6]:
np.max(df,axis = 0 )

array([24, 47, 41, 61, 20, 59, 29, 22])

In [8]:
np.min(df,axis = 0)

array([0, 0, 0, 0, 0, 0, 0, 0])